name: ML Pipeline - Train Model and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать workflow вручную

env:
  PYTHON_VERSION: '3.12'
  S3_BUCKET_NAME: ml-model-storage
  S3_ENDPOINT: https://storage.yandexcloud.net
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  YC_SA_JSON_CREDENTIALS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}


jobs:
  train:
    runs-on: ubuntu-latest
    name: Train Iris Model and Upload to S3
    
    steps:
    # загрузка репозитория в runner
    - name: Checkout code
      uses: actions/checkout@v4
    
    # настройка Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # запуск обучения модели
    - name: Run model training
      env:
        S3_ACCESS_KEY: ${{ env.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ env.S3_SECRET_KEY }}
        S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
      run: |
        cd src
        python train.py

  deploy-function:
    name: Deploy Serverless Function
    runs-on: ubuntu-latest
    # needs: [train]  # Запускается после обучения модели и загрузки кода
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy Function to Yandex Cloud
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-json-credentials: ${{ env.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ env.YC_FOLDER_ID }}
          service-account-name: 'github-actions-sa'
          function-name: 'ml-predict-api'
          runtime: 'python312'
          memory: '512Mb'
          entrypoint: 'main.handler'
          execution-timeout: '60'
          environment: |
            S3_ACCESS_KEY=${{ env.S3_ACCESS_KEY }}
            S3_SECRET_KEY=${{ env.S3_SECRET_KEY }}
            S3_BUCKET_NAME=${{ env.S3_BUCKET_NAME }}
          include: |
            ./main.py
            ./requirements.txt
          exclude: |
            ./**/*.md
            ./**/.git*

